---
- rule:
    path: /specification/cdn
    reviewers:
      - ruowan
      - raych1

- rule: 
    path: /specification/network
    reviewers:
      - ruowan

- rule: 
    path: /specification/**/date-plane
    reviewers:
    - Dreamgoing