---
- rule:
    path: "documentation/**"
    reviewers:
      - ruowan
      - raych1

- rule:
    path: "specification/**/Microsoft.Network/**"
    reviewers:
      - ruowan
      - NullMDR
      - Dreamgoing

- rule:
    path: "specification/**/date-plane/**"
    reviewers:
      - Dreamgoing

- rule:
    path: "specification/**/resource-manager/**"
    reviewers:
      - NullMDR
      - ruowan

- rule:
    path: "**"
    reviewers:
      - ruowan
