---
- rule:
    booleanFilterExpression: "Java"
    assignees:
      - ruowan
- rule:
    booleanFilterExpression: "Python"
    assignees:
      - ruowan
      - NullMDR

- rule:
    booleanFilterExpression: "triage"
    assignees:
      - ruowan
      - Dreamgoing
      - NullMDR
