--- 
- group:
    name: default
    users:
        - githubID: userA
          email: userA@microsoft.com
        - githubID : someone
          email: someone@microsoft.com
        - githubID: ruowan
          email: ruowan@microsoft.com
        - githubID: raych1
          email: raychen@microsoft.com
      
- group:
    name: teamB
    users: 
        - githubID: xxx
          email: xxx@microsoft.com