---
- scheduleTask:
    action: sendEmailToAssignee
    trigger: 
      - time
    args:
      booleanFilterExpression: "!(WaitForARMFeedback||DoNotMerge||WaitingForAzureAPIBoard)"
      limit: 100d
      message: '<p> Dear Swagger reviewer, <br> <br> Please response to the PR ${PR_URL}. The PR isn''t updated in 48 hours. <br> <hr /> <br> Quick info. <ul> <li>If no response from ARM review board, please send email to armapireview@microsoft.com.</li> <li>If need immediate ARM review, please get ARM review oncall contact point from ICM https://icm.ad.msft.net/imp/v3/oncall/current under Service "Azure Resource Manager" and Team "RP Manifest Approvers"</li> <li>If no response from Azure API review board, please send email to azureapirbcore@microsoft.com.</li> <li>If you have problem to fix CI task errors, please send email to Visual Studio China Swagger and Tool team vscswagger@microsoft.com.</li> <li>If you want to opt out from Swagger reviewing for out of office period, please set vacation date at https://inframonitorweb1.azurewebsites.net/Home/MyView.</li> <li>Pls refer to <a href="onenote:https://microsoft.sharepoint.com/teams/IoTToolingTeam/SiteAssets/IoT Tooling Team Notebook/Azure Management Experience - transition.one#Swagger%20reviewing%20process§ion-id={ECE847C4-519B-4448-A1A0-8E84A7EFE8AB}&page-id={F6E345FE-46E1-420F-B837-6BF76167DE05}&end">Swagger review process (onenote)</a> for more about Swagger review process.</li> </ul> Best regards, <br> Azure Management Experience </p>'
      subject: "Action Required: Please respond to PR ${PR_URL}"
    description: "None initial response in 48 hours"
    scope: pull_request
    name: no-initial-response

- scheduleTask:
    action: sendEmailToAssignee
    trigger: 
      - time
      - label
    args:
      booleanFilterExpression: "!(WaitForARMFeedback||DoNotMerge||WaitingForAzureAPIBoard||ARMSignedOff||AzureAPIBoardSignedOff)"
      limit: 100d
      message: '<p> Dear Swagger reviewer, <br> <br> Please response to the PR ${PR_URL}. The PR isn''t updated in 5 days. <br> <hr /> <br> Quick info. <ul> <li>If no response from ARM review board, please send email to armapireview@microsoft.com.</li> <li>If need immediate ARM review, please get ARM review oncall contact point from ICM https://icm.ad.msft.net/imp/v3/oncall/current under Service "Azure Resource Manager" and Team "RP Manifest Approvers"</li> <li>If no response from Azure API review board, please send email to azureapirbcore@microsoft.com.</li> <li>If you have problem to fix CI task errors, please send email to Visual Studio China Swagger and Tool team vscswagger@microsoft.com.</li> <li>If you want to opt out from Swagger reviewing for out of office period, please set vacation date at https://inframonitorweb1.azurewebsites.net/Home/MyView.</li> <li>Pls refer to <a href="onenote:https://microsoft.sharepoint.com/teams/IoTToolingTeam/SiteAssets/IoT Tooling Team Notebook/Azure Management Experience - transition.one#Swagger%20reviewing%20process§ion-id={ECE847C4-519B-4448-A1A0-8E84A7EFE8AB}&page-id={F6E345FE-46E1-420F-B837-6BF76167DE05}&end">Swagger review process (onenote)</a> for more about Swagger review process.</li> </ul> Best regards, <br> Azure Management Experience </p>'
      subject: "Action Required: Please respond to PR ${PR_URL}"
    description: "None update in PR in 5 days"
    name: no-update-in-5d
    scope: pull_request
    repoWhitelist:
      - ruowan-test/sla-test-repo-pr

- scheduleTask:
    action: sendEmail
    trigger: 
      - time
    args:
      booleanFilterExpression: "!ARMChangesRequested && !ARMReviewInProgress && WaitForARMFeedback"
      limit: 100s
      subject: "Action Required: Please help to review PR ${PR_URL}"
      message: "<p> Dear ARM review board, <br> <br>Please review PR ${PR_URL}, the PR is waiting for ARM review over 3 days. Thanks.<br><hr /> <br>Quick info<ul><li>If you have feedback about the notification email, please contact us at vscswagger@microsoft.com.</li><li>After reviewing, please remove “WaitForARMFeedback” label from PR to avoid receiving notification on the same PR.</li><li>Please do not reply to this email, this is an automatic generated email.</li></ul>Best regards,<br> Azure Management Experience</p>"
      to: ruowan@microsoft.com
    description: "single email point"
    name: "arm team"
    scope: pull_request
    repoWhitelist:
      - ruowan-test/sla-test-repo

- scheduleTask:
    action: sendEmail
    trigger: 
      - time
    args:
      booleanFilterExpression: "Mgnt"
      limit: 5s
      subject: "Action Required: Please response to issues ${URL}"
      message: "Please response to the issues ${URL}"
      from: xxx@microsoft.com
      to: 
        - ruowan@microsoft.com
        - tih@microsoft.com
      cc:
        - qiaozha@microsoft.com
    description: "issue triage"
    name: "issue owner"
    scope: issue
    repoWhitelist:
      - ruowan-test/sla-test-repo

- scheduleTask:
    action: sendEmailToAssignee
    trigger: time
    args:
      booleanFilterExpression: "Mgnt"
      limit: 5s
      subject: "Action Required: Please response to issues ${URL}"
      message: "Please response to the issues ${URL}. send email to assignee"
      from: xxx@microsoft.com
      cc:
        - qiaozha@microsoft.com
    description: "issue triage"
    name: "issue owner"
    scope: issue
    repoWhitelist:
      - ruowan-test/sla-test-repo
      

- scheduleTask:
    action: sendEmail
    scope: pull_request
    trigger: 
      - label
      - time
    args: 
      booleanFilterExpression: "LinterRuleCandidate"
      limit: 10s
      message: "Dear Swagger reviewer. Please review this LinterRuleCandidate PR"
      subject: "Action Required: Please review the linterRuleCandidate PR"
      to: ruowan@microsoft.com